<a href="https://colab.research.google.com/github/AivinBinoy/AivinBinoy/blob/main/Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

df = pd.read_csv('student_data_100_preprocess.csv')

In [4]:

df.head()

   Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
0    Male   NaN            1.0        65.0           Graduate         95.0
1  Female  21.0            1.0        80.0           Graduate         70.0
2    Male   NaN            3.0        60.0       Postgraduate         60.0
3    Male  21.0            2.0        60.0        High School         80.0
4    Male  20.0            5.0        80.0           Graduate          NaN

In [5]:

df.tail()

    Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
95  Female  18.0            6.0         NaN       Postgraduate         65.0
96  Female  20.0            6.0        95.0        High School          NaN
97  Female  20.0            3.0        80.0                NaN         75.0
98  Female  18.0            6.0        60.0                NaN         50.0
99    Male  19.0            8.0        90.0                NaN         90.0

In [6]:

df.shape

(100, 6)

In [7]:

df.columns

Index(['Gender', 'Age', 'Hours_Studied', 'Attendance', 'Parental_Education',
       'Final_Score'],
      dtype='object')

In [8]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Gender              100 non-null    object
 1   Age                 91 non-null     float64
 2   Hours_Studied       90 non-null     float64
 3   Attendance          92 non-null     float64
 4   Parental_Education  87 non-null     object
 5   Final_Score         93 non-null     float64
dtypes: float64(4), object(2)
memory usage: 4.8+ KB

In [9]:

num_cols = df.select_dtypes(include=['int64','float64'])
print(num_cols.columns)

cat_cols = df.select_dtypes(include=['object'])
print(cat_cols.columns)

Index(['Age', 'Hours_Studied', 'Attendance', 'Final_Score'], dtype='object')
Index(['Gender', 'Parental_Education'], dtype='object')

In [10]:
df.describe()

             Age  Hours_Studied  Attendance  Final_Score
count  91.000000      90.000000   92.000000    93.000000
mean   19.417582       4.366667   76.684783    74.247312
std     1.174412       2.348559   11.843234    14.632198
min    18.000000       1.000000   60.000000    50.000000
25%    18.000000       3.000000   65.000000    60.000000
50%    19.000000       4.000000   77.500000    75.000000
75%    21.000000       6.000000   85.000000    90.000000
max    21.000000       8.000000   95.000000    95.000000

In [11]:
df.isnull().sum()

Gender                 0
Age                    9
Hours_Studied         10
Attendance             8
Parental_Education    13
Final_Score            7
dtype: int64

In [12]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Hours_Studied'].fillna(df['Hours_Studied'].mean(), inplace=True)
df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)
df['Final_Score'].fillna(df['Final_Score'].mean(), inplace=True)

/tmp/ipykernel_6130/1775224795.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipykernel_6130/1775224795.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Hours_Studied'].fillna(df['Hours_Studied'].mean(), inplace=True)
/tmp/ipykernel_6130/1775224795.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)
/tmp/ipykernel_6130/1775224795.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Final_Score'].fillna(df['Final_Score'].mean(), inplace=True)

In [13]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Parental_Education'].fillna(df['Parental_Education'].mode()[0], inplace=True)

/tmp/ipykernel_6130/3980834269.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
/tmp/ipykernel_6130/3980834269.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Parental_Education'].fillna(df['Parental_Education'].mode()[0], inplace=True)

In [14]:
df.isnull().sum()

Gender                0
Age                   0
Hours_Studied         0
Attendance            0
Parental_Education    0
Final_Score           0
dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['Gender']

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    0
97    0
98    0
99    1
Name: Gender, Length: 100, dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Gender                           100 non-null    int64
 1   Age                              100 non-null    float64
 2   Hours_Studied                    100 non-null    float64
 3   Attendance                       100 non-null    float64
 4   Final_Score                      100 non-null    float64
 5   Parental_Education_Graduate      100 non-null    bool
 6   Parental_Education_High School   100 non-null    bool
 7   Parental_Education_Postgraduate  100 non-null    bool
dtypes: bool(3), float64(4), int64(1)
memory usage: 4.3 KB

In [22]:
from sklearn.model_selection import train_test_split

X = df.drop('Final_Score', axis=1)
y = df['Final_Score']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [23]:
print(X_train.shape, X_test.shape)

(80, 7) (20, 7)